dist: bionic
services:
  - xvfb
language: node_js
node_js:
  - node

cache: npm

before_install:
  - sudo apt-get -y install xsel
  - chmod +x ./bin/run

script:
  - ./bin/run --version
  - ./bin/run --help
  - npm run test

after_success:
  - ./node_modules/.bin/nyc report --reporter text-lcov > coverage.lcov
  - bash < (curl -s https://codecov.io/bash)